name: 'WakeMeOps'
description: 'Add WakeMeOps Debian repository and install packages'
inputs:
  packages:
    description: 'List of packages to install'
    required: false
runs:
  using: "composite"
  steps:
    - name: Install WakeMeOps repository
      run: |
        sudo ${{ github.action_path }}/install_repository
      shell: bash

    - name: Install packages
      run: |
        sudo ${{ github.action_path }}/install_packages $(echo -n "${{ inputs.packages }}")
      shell: bash
