name: 🚀 CI/CD

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packages
        uses: ./
        with:
          packages: |
            ops2deb
            make
